version: "3.9"

services:
  vite:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app/apps/react-vite
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  webpack:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app/apps/react-webpack
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

  cra:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app/apps/react-cra
    ports:
      - "3001:3000"
    command: sh -c "npm install && npm start"
