version: "3.9"

services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # コンテナ内で実行するコマンド → コンテナ内で実行するコマンドを指定する
    command: npm run dev -- --host 0.0.0.0 --port 5173

